dependencies:
  # - <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  mainnet-fork:
    verify: False
wallets:
  DEV01: ${PRIVATE_KEY_1}
  DEV02: ${PRIVATE_KEY_2}
  DEV03: ${PRIVATE_KEY_3}